### ISSUE TITLE
Multitask `api.learner` needs to handle dictionaries of targets.

### ISSUE THREAD

**Issue by yngtodd** [yngtodd/bayescache#4]
Need to handle `targets` passed as dictionaries in the multitask case within `api.learner`.

```
Traceback (most recent call last):
  File "mtcnn_p3b3.py", line 54, in <module>
    main()
  File "mtcnn_p3b3.py", line 50, in main
    learner.train_epoch(epoch_info, source)
  File "/home/ygx/src/develop/bayescache/bayescache/api/learner.py", line 71, in train_epoch
    self.train_batch(batch_info, data, target)
  File "/home/ygx/src/develop/bayescache/bayescache/api/learner.py", line 106, in train_batch
    loss = self.feed_batch(batch_info, data, target)
  File "/home/ygx/src/develop/bayescache/bayescache/api/learner.py", line 92, in feed_batch
    data, target = data.to(self.device), target.to(self.device)
AttributeError: 'dict' object has no attribute 'to'
```

**Comment by yngtodd** [comment]
Start of the issue:  https://github.com/yngtodd/bayescache/blob/master/bayescache/api/learner.py#L90
